##baseURL = "http://localhost"
baseURL = "http://test-show.zzz.com.ua"
title = "MDL - Talent Hub Blog"
DefaultContentLanguage = "en"
preserveTaxonomyNames = true

[taxonomies]
    category = "categories"
[params]
  keywords = "MDL,blockchain,talents,models,technology,app,IPFS"
  description = "Blog of MDL Talent Hub. We create blockchain powered platform for talent sourcing industry."
  telegram = "https://t.me/MDL_Talent_Hub"
  sidebar_sub_title = "Learn about the"
  sidebar_sub_title_pink = "latest news"
  subscribe_title = "Subscribe to the MDL Newsletter"
  subscribe_title_footer = "Sign up for timely alerts and announcements"
  allTopicsTranslate = "All topics"
  subscribeButton = "Subscribe"

[[params.social]]
urlImage = "img/sidebar/fb.svg"
link = "https://www.facebook.com/mdl.wtf"
[[params.social]]
urlImage = "img/sidebar/twitter.svg"
link = "https://twitter.com/MDL_Talent_Hub"
[[params.social]]
urlImage = "img/sidebar/fb.svg"
link = "https://www.facebook.com/mdl.wtf"
[[params.social]]
urlImage = "img/sidebar/twitter.svg"
link = "https://twitter.com/MDL_Talent_Hub"
[[params.social]]
urlImage = "img/sidebar/fb.svg"
link = "https://www.facebook.com/mdl.wtf"

[languages]
  [languages.en]
    languageName = "Eng"
    weight = 1
    sidebar_sub_title = "Learn about the"
    sidebar_sub_title_pink = "latest news"
    subscribe_title = "Subscribe to the MDL Newsletter"
    subscribe_title_footer = "Sign up for timely alerts and announcements"
    allTopicsTranslate = "All topics"
    subscribeButton = "Subscribe"
  [languages.ru]
    languageName = "Рус"
    weight = 2
    sidebar_sub_title = "Узнайте"
    sidebar_sub_title_pink = "последние новости"
    subscribe_title = "Подпишись на рассылку новостей MDL"
    subscribe_title_footer = "Подпишись и узнай последние новости"
    allTopicsTranslate = "Все темы"
    subscribeButton = "Подписаться"
  [languages.zh]
      languageName = "简体"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.zh-hant]
      languageName = "繁體"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.kr]
      languageName = "한글"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.ja]
      languageName = "日本語"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.es]
      languageName = "ES"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.id]
      languageName = "ID"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.de]
      languageName = "DE"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"
  [languages.ar]
      languageName = "عربي"
      weight = 2
      sidebar_sub_title = "Learn about the"
      sidebar_sub_title_pink = "latest news"
      subscribe_title = "Subscribe to the MDL Newsletter"
      subscribe_title_footer = "Sign up for timely alerts and announcements"
      allTopicsTranslate = "All topics"
      subscribeButton = "Subscribe"